/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/common/BackButton.vue')['default']
    BreadcrumbNav: typeof import('./src/components/common/BreadcrumbNav.vue')['default']
    Carousel: typeof import('./src/components/home/Carousel.vue')['default']
    CompanyIntro: typeof import('./src/components/home/CompanyIntro.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EnvironmentControl: typeof import('./src/components/smart-farm/EnvironmentControl.vue')['default']
    FarmMonitor: typeof import('./src/components/smart-farm/FarmMonitor.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    NewsAnnouncement: typeof import('./src/components/home/NewsAnnouncement.vue')['default']
    RobotStatus: typeof import('./src/components/smart-farm/RobotStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemModules: typeof import('./src/components/home/SystemModules.vue')['default']
    VideoMonitor: typeof import('./src/components/services/VideoMonitor.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
